### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by AddalaTejaswini** [SouravSahu/GEC#1]
We get error on Cell [56] as described below:
OSError                                   Traceback (most recent call last)
<ipython-input-56-4a8b2157f8e7> in <module>()
----> 1 model.load_weights('drive/MyDrive/Copy of 01-04-model-ep004-loss0.421-val_loss1.184.h5')

3 frames
/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    140         if swmr and swmr_support:
    141             flags |= h5f.ACC_SWMR_READ
--> 142         fid = h5f.open(name, flags, fapl=fapl)
    143     elif mode == 'r+':
    144         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

**OSError: Unable to open file (unable to open file: name = 'drive/MyDrive/Copy of 01-04-model-ep004-loss0.421-val_loss1.184.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)**

**Comment by SouravSahu** [comment]
I had weights stored on my drive for my work to be resumed without training the whole model again. You can re-train the model to get those weights and skip these lines.
